name: modern_app_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animate_do: ^3.3.4
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  firebase_database: ^11.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/translations/
    - assets/svg/

  fonts:
    - family: NewRocker
      fonts:
        - asset: assets/fonts/new_rocker.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic